version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
    - POSTGRES_USER=git-gud
    - POSTGRES_PASSWORD=git-gud
    ports:
    - 5432:5432

  migrations:
    build: back/migrations/
    restart: "no"
    command:
    - -database=postgres://git-gud:git-gud@db/git-gud?sslmode=disable
    - up
    depends_on:
    - db

  postgraphile:
    build: back/
    environment:
      DATABASE_URL: "postgres://git-gud:git-gud@db/git-gud?sslmode=disable"
      OIDC_ISSUER: "https://ndli-2k19.eu.auth0.com/"
    ports:
    - 3000:3000

  notifs:
    build: notifs/
    environment:
      PGHOST: db
      PGDATABASE: git-gud
      PGUSER: git-gud
      PGPASSWORD: git-gud
      WEB_PUSH_CONTACT: "mailto:paul.heng@etu.unistra.fr"
      PUBLIC_VAPID_KEY: "BOH8nTQA5iZhl23+NCzGG9prvOZ5BE0MJXBW+GUkQIvRVTVB32JxmX0V1j6z0r7rnT7+bgi6f2g5fMPpAh5brqM="
      PRIVATE_VAPID_KEY: "TRlY/7yQzvqcLpgHQTxiU5fVzAAvAw/cdSh5kLFLNqg="
    depends_on:
    - migrations

      # front:
      #   build: front/
      #   ports:
      #   - 8080:80
