version: '3'

services:
  db:
    image: postgres:12-alpine
    environment:
    - POSTGRES_USER=git-gud
    - POSTGRES_PASSWORD=git-gud
    ports:
    - 5432:5432

  migrations:
    build: back/migrations/
    restart: "no"
    command:
    - -database=postgres://git-gud:git-gud@db/git-gud?sslmode=disable
    - up
    depends_on:
    - db

  postgraphile:
    image: graphile/postgraphile:4
    environment:
      PGHOST: db
      PGDATABASE: git-gud
      PGUSER: git-gud
      PGPASSWORD: git-gud
    depends_on:
    - migrations
    command: -s api -r anonymous
    ports:
    - 5000:5000
