apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: traefik

namespace: traefik

resources:
- crd.yaml
- rbac.yaml
- service.yaml
- deployment.yaml
- ingress.yaml
