apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifs
spec:
  template:
    spec:
      containers:
      - name: notifs
        image: docker.pkg.github.com/git-gud-ndli/ndli2k19/notifs:latest
        imagePullPolicy: Always
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: url
        - name: WEB_PUSH_CONTACT
          value: "mailto:paul.heng@etu.unistra.fr"
        - name: PUBLIC_VAPID_KEY
          value: "BOH8nTQA5iZhl23+NCzGG9prvOZ5BE0MJXBW+GUkQIvRVTVB32JxmX0V1j6z0r7rnT7+bgi6f2g5fMPpAh5brqM="
        - name: PRIVATE_VAPID_KEY
          value: "TRlY/7yQzvqcLpgHQTxiU5fVzAAvAw/cdSh5kLFLNqg="
        - name: PGHOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: host
        - name: PGDATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db
        - name: PGUSER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: user
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: pass
