name: Publish Back Docker image

on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master

    - name: Publish Docker Image to GPR
      uses: machine-learning-apps/gpr-docker-publish@master
      id: docker
      with:
        IMAGE_NAME: 'back'
        TAG: 'latest'
        DOCKERFILE_PATH: 'back/Dockerfile'
        BUILD_CONTEXT: 'back/'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
